import ElCarro from './img/El_Carro.png'
import ElDiablo from './img/El_Diablo.png'
import ElEmperador from './img/El_Emperador.png'
import ElJuicio from './img/El_Juicio.png'
import ElMundo from './img/El_Mundo.jpg'
import ElSol from './img/El_Sol.png'
import Sacerdote from './img/El_Sumo_Sacerdote.png'
import LaColgada from './img/La_Colgada.png'
import LaEmperatriz from './img/La_Emperatriz.png'
import LaErmitania from './img/La_Ermitania.png'
import LaEstrella from './img/La_Estrella.png'
import LaFuerza from './img/La_Fuerza.png'
import LaJusticia from './img/La_Justicia.png'
import LaLoca from './img/La_Loca.png'
import LaLuna from './img/La_Luna.png'
import LaMaga from './img/La_Maga.png'
import LaMuerte from './img/La_Muerte.png'
import LaRueda from './img/La_Rueda.png'
import LaTemplanza from './img/La_Templanza.png'
import LaTorre from './img/La_Torre.png'
import LxsEnamorados from './img/Lxs_Enamoradxs.png'
import Sacerdotiza from './img/Sacerdotiza.png'

const Imports = [ElCarro, ElDiablo, ElEmperador, ElJuicio, ElMundo, ElSol, Sacerdote, LaColgada, LaEmperatriz, LaErmitania, LaEstrella, LaFuerza, LaJusticia, LaLoca, LaLuna, LaMaga, LaMuerte, LaRueda, LaTemplanza, LaTorre, LxsEnamorados, Sacerdotiza]; 
export default Imports;