import ElCarro from './img/El_Carro.jpeg'
import ElDiablo from './img/El_Diablo.jpeg'
import ElEmperador from './img/El_Emperador.jpeg'
import ElJuicio from './img/El_Juicio.jpeg'
import ElMundo from './img/El_Mundo.jpeg'
import ElSol from './img/El_Sol.jpeg'
import Sacerdote from './img/El_Sumo_Sacerdote.jpeg'
import LaColgada from './img/La_Colgada.jpeg'
import LaEmperatriz from './img/La_Emperatriz.jpeg'
import LaErmitania from './img/La_Ermitania.jpeg'
import LaEstrella from './img/La_Estrella.jpeg'
import LaFuerza from './img/La_Fuerza.jpeg'
import LaJusticia from './img/La_Justicia.jpeg'
import LaLoca from './img/La_Loca.jpeg'
import LaLuna from './img/La_Luna.jpeg'
import LaMaga from './img/La_Maga.jpeg'
import LaMuerte from './img/La_Muerte.jpeg'
import LaRueda from './img/La_Rueda.jpeg'
import LaTemplanza from './img/La_Templanza.jpeg'
import LaTorre from './img/La_Torre.jpeg'
import LxsEnamorados from './img/Lxs_Enamoradxs.jpeg'
import Sacerdotiza from './img/Sacerdotiza.jpeg'

const Imports = [ElCarro, ElDiablo, ElEmperador, ElJuicio, ElMundo, ElSol, Sacerdote, LaColgada, LaEmperatriz, LaErmitania, LaEstrella, LaFuerza, LaJusticia, LaLoca, LaLuna, LaMaga, LaMuerte, LaRueda, LaTemplanza, LaTorre, LxsEnamorados, Sacerdotiza]; 
export default Imports;